version: '3.7'

services:

  web:
    # replace username/repo:tag with your name and image details
    image: pnguy55/calc-new:new
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 100M
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
